# Generated by Django 5.2.4 on 2025-08-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_game_initial_fen'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_color',
            field=models.CharField(default='white', max_length=5),
        ),
    ]
