# Generated by Django 5.2.4 on 2025-09-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_game_player_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_fen',
            field=models.CharField(default=models.CharField(default='start', max_length=100), max_length=100),
        ),
    ]
